### ISSUE TITLE
Failed at the scalable-react-boilerplate@1.1.0 test script 'cross-env BABEL_DISABLE_CACHE=1 NODE_ENV=test node --harmony_proxies node_modules/.bin/jest

### ISSUE THREAD

**Issue by krrssna-g-s** [RyanCCollins/scalable-react-boilerplate#49]
Getting error on Node version 7.1.0

```
npm run test

> scalable-react-boilerplate@1.1.0 test /Users/srikrishnagumma/Desktop/Projects/scalable-react-boilerplate
> cross-env BABEL_DISABLE_CACHE=1 NODE_ENV=test node --harmony_proxies node_modules/.bin/jest

node: bad option: --harmony_proxies

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/Cellar/node/7.1.0/bin/node" "/usr/local/bin/npm" "run" "test"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! scalable-react-boilerplate@1.1.0 test: `cross-env BABEL_DISABLE_CACHE=1 NODE_ENV=test node --harmony_proxies node_modules/.bin/jest`
npm ERR! Exit status 9
npm ERR! 
npm ERR! Failed at the scalable-react-boilerplate@1.1.0 test script 'cross-env BABEL_DISABLE_CACHE=1 NODE_ENV=test node --harmony_proxies node_modules/.bin/jest'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the scalable-react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env BABEL_DISABLE_CACHE=1 NODE_ENV=test node --harmony_proxies node_modules/.bin/jest
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs scalable-react-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls scalable-react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/srikrishnagumma/Desktop/Projects/scalable-react-boilerplate/npm-debug.log

```

**Comment by cramhead** [comment]
All my tests fail too. 
I get another error though. All errors are of the form:
```
 FAIL  app/src/components/About/tests/index.test.js
  ● Test suite failed to run

    /Users/mdentremont/Projects/REACT/scalable-react-boilerplate/app/src/components/About/tests/index.test.js: Cannot find module '/Users/mdentremont/Projects/REACT/scalable-react-boilerplate/config/testing/webpack.test.config.js'

      at Function.Module._resolveFilename (module.js:469:15)
      at Function.Module._load (module.js:417:25)
      at Module.require (module.js:497:17)
      at require (internal/module.js:20:19)
      at localInteropRequire (node_modules/babel-plugin-webpack-loaders/lib/plugin.js:225:13)
      at PluginPass.CallExpression (node_modules/babel-plugin-webpack-loaders/lib/plugin.js:41:58)
      at newFn (node_modules/babel-traverse/lib/visitors.js:276:21)
      at NodePath._call (node_modules/babel-traverse/lib/path/context.js:76:18)
      at NodePath.call (node_modules/babel-traverse/lib/path/context.js:48:17)
      at NodePath.visit (node_modules/babel-traverse/lib/path/context.js:105:12)

Test Suites: 14 failed, 14 total
Tests:       0 total
Snapshots:   0 total
Time:        1.34s
Ran all test suites.
```
